### ISSUE TITLE
Threads don't work.

### ISSUE THREAD

**Issue by TannerRogalsky** [TannerRogalsky/love.js#1]
Firefox has experimental support for threads but general support seems like it's still a long way off.

https://kripken.github.io/emscripten-site/docs/porting/pthreads.html

**Comment by davisdude** [comment]
You probably know a lot more about this than I do, but have you read [this](http://flohofwoe.blogspot.com/2013/01/multithreading-in-emscripten-with-html5.html)?

**Comment by TannerRogalsky** [comment]
Yeah, it's either pthreads in Firefox Nightly or WebWorkers. Neither of which are a very good solution right now.

**Comment by TannerRogalsky** [comment]
Threads work in 0.11/
