### ISSUE TITLE
Not able to scroll

### ISSUE THREAD

**Issue by davisdude** [TannerRogalsky/love.js#11]
You aren't able to scroll the page with mousewheel or arrow/keys (when game is not selected).

**Comment by TannerRogalsky** [comment]
I can't reproduce this with a mousewheel. What's your browser, OS, and the resolution of your browser window.

**Comment by davisdude** [comment]
Google Chrome, Windows 8 (running 10), 1366x768. If it helps I'm also using a plug-in Logitech Wireless mouse.

**Comment by TannerRogalsky** [comment]
@davisdude I can't reproduce this in Chrome on Windows with your resolution. The mousewheel scrolls fine.

**Comment by davisdude** [comment]
The mouse also has to be over the screen area for it to not scroll.

**Comment by TannerRogalsky** [comment]
@davisdude That's intended.
