### ISSUE TITLE
SyntaxError: Missing parentheses in call to 'print'

### ISSUE THREAD

**Issue by Khranos** [TannerRogalsky/love.js#13]
When I attempt to build my game (currently a .love file), I receive the following error --

File "../emscripten/tools/file_packager.py", line 69 
See the source for more details.'''
SyntaxError: Missing parentheses in call to 'print'

I'm using this command in a bash inside of the debug folder --

python ../emscripten/tools/file_packager.py game.data --preload C:/Users/(removing rest of path for security).love@/ --js-output=game.js

This may be user error, though I'm adding this just in case it isn't.

Operating System: Windows 7

**Comment by kripken** [comment]
What version of Python is used? Python 3 requires parentheses on print, while 2 does not, so that could explain the error. The emscripten file packager (and the rest of emscripten as well) requires Python 2.

**Comment by Khranos** [comment]
That turned out to be correct. After replacing 3.5 with 2.7, everything appears to be running smoothly -- no more errors. 

If this is read by TannerRogalsky, I'd suggest adding something to the dependencies that Python 3 isn't supported to help alleviate any more erroneous "issues" like this one.

**Comment by JanWerder** [comment]
https://github.com/TannerRogalsky/love.js/pull/15
