### ISSUE TITLE
Compiling under Windows

### ISSUE THREAD

**Issue by JanWerder** [TannerRogalsky/love.js#14]
I'm trying to compile my Löve game under Windows 10 with Python 2.7

`python ../emscripten/tools/file_packager.py game.data --preload C:\Users\janwe\Documents\GitHub\game@/ --js-output=game.js`

Gives me the following error:

C:\Users\janwe\nak\lovejs\love.js\debug>python ../emscripten/tools/file_packager.py game.data --preload C:\Users\janwe\Documents\GitHub\game\@/ --js-output=game.js
Traceback (most recent call last):
  File "../emscripten/tools/file_packager.py", line 255, in <module>
    os.path.walk(file_['srcpath'], add, [file_['mode'], file_['srcpath'], file_['dstpath']])
  File "C:\Python27\lib\ntpath.py", line 273, in walk
    walk(name, func, arg)
  File "C:\Python27\lib\ntpath.py", line 273, in walk
    walk(name, func, arg)
  File "C:\Python27\lib\ntpath.py", line 269, in walk
    func(arg, top, names)
  File "../emscripten/tools/file_packager.py", line 240, in add
    if should_ignore(fullname):
  File "../emscripten/tools/file_packager.py", line 219, in should_ignore
    if has_hidden_attribute(fullname):
  File "../emscripten/tools/file_packager.py", line 209, in has_hidden_attribute
    attrs = ctypes.windll.kernel32.GetFileAttributesW(unicode(filepath))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xfc in position 74: ordinal not in range(128)

C:\Users\janwe\nak\lovejs\love.js\debug>

**Comment by TannerRogalsky** [comment]
@JanWerder Does one of your files or directories have a non-ascii character in it's file path? Non-ascii characters in file paths on windows seems to cause problems.

**Comment by JanWerder** [comment]
This was indeed the error. I had a library called sölar and renaming it to solar resolved this issue

**Comment by TannerRogalsky** [comment]
If someone really desperately wants to use non-ASCII characters in their filenames on Windows, consider resolving this issue: https://github.com/kripken/emscripten/pull/4102

**Comment by JanWerder** [comment]
Thank you for finding the root cause :)
