### ISSUE TITLE
Detecting the platform.

### ISSUE THREAD

**Issue by Bobbyjoness** [TannerRogalsky/love.js#19]
Love currently has a way to retrieve the OS through love.system.getOS. Although the web is not an OS maybe it can be added in there so people can make code branches for web or desktop.

**Comment by TannerRogalsky** [comment]
Yep, easy.

**Comment by TannerRogalsky** [comment]
As of 16288c2, `love.system.getOS` should return 'Web' in emscripten builds.

https://bitbucket.org/TannerRogalsky/love/commits/24683ea5cd793d5e98d3d26d3ceb2e9b738df905
