### ISSUE TITLE
Mobile Support

### ISSUE THREAD

**Issue by JaredSartin** [TannerRogalsky/love.js#29]
Testing Mari0 in iOS 9 Safari (yes I know controls won't work) ends up erroring out when loading:

```
11950104 - Exception catching is disabled, this exception cannot be caught. Compile with -s DISABLE_EXCEPTION_CATCHING=0 or DISABLE_EXCEPTION_CATCHING=2 to catch.
  callMainlove.js:23:11938
  setStatusmari0:76
  (anonymous function)love.js:23:12543
```

Wondering if there has been consideration for mobile web support?

**Comment by TannerRogalsky** [comment]
Pretty sure Mari0 has joystick enabled. Won't work in mobile or safari. #24 is important for solving this.

**Comment by JaredSartin** [comment]
Not gonna re-open - but that exception is generated from the Joystick problem?

**Comment by TannerRogalsky** [comment]
I think so. I've been through a lot of stuff since then but when I last tried stuff on Safari that looked like the problem.

**Comment by JaredSartin** [comment]
Sounds good. I will then continue conversation/findings on #24 

Cheers!
