### ISSUE TITLE
bad argument #2 to 'random' (interval is empty)

### ISSUE THREAD

**Issue by spectrenoir06** [TannerRogalsky/love.js#31]
Hello i have encounter a strange error with math.random(100, -100)

Error
----
![capture d ecran de 2016-03-12 20 42 45](https://cloud.githubusercontent.com/assets/5509337/13724895/fbdd595a-e893-11e5-82a5-5baf2f879dea.png)

Weapon.lua
----
![capture d ecran de 2016-03-12 20 46 35](https://cloud.githubusercontent.com/assets/5509337/13724896/fbddcfb6-e893-11e5-8f8e-41e66961981b.png)

**Comment by TannerRogalsky** [comment]
Your code throws an error in Lua. You probably want to reverse the arguments to `math.random` if you're trying to get a random number between -100 and 100. You will see similar errors when running your game using the native love executable.

http://www.lua.org/manual/5.1/manual.html#pdf-math.random

**Comment by spectrenoir06** [comment]
Thank's for the short response

I have understand the probleme i'ts because love.js use standart Lua and Löve use luaJIT

```
Lua 5.2.3  Copyright (C) 1994-2013 Lua.org, PUC-Rio
> print(math.random(100,-100))
stdin:1: bad argument #2 to 'random' (interval is empty)
stack traceback:
	[C]: in function 'random'
	stdin:1: in main chunk
	[C]: in ?
```


```
LuaJIT 2.0.3 -- Copyright (C) 2005-2014 Mike Pall. http://luajit.org/
> print(math.random(100,-100))
-59

```

**Comment by TannerRogalsky** [comment]
@spectrenoir06 Ah, very true. That's pretty weird. Thanks for figuring that out!
