### ISSUE TITLE
Game doesn't load up properly and freeze

### ISSUE THREAD

**Issue by MadByteDE** [TannerRogalsky/love.js#34]
Game doesn't load up properly and freeze immediately (everytime) if the game data on the server is newer then the local version. If that happen I reload the page (a second time) and everything is fine.

The issue show up in two different ways:
1. The game shows up in blank black color after loading and doesn't respond.
2. The first game frame get displayed but freezes.

The problem just occurs if the game data has been updated and need to be downloaded again. I guess it might be a problem with the previous game version in the browser cache, anyway I think this shouldn't happen.

Browser: Chrome (64bit)
Windows 7 64bit

**Comment by TannerRogalsky** [comment]
@MadByteDE Does this happen with every game you try? How often does it happen (1 in 10, every second time)?

**Comment by MadByteDE** [comment]
1. If I have **a local copy** of my game in the cache, then update it and reload the page - its 10 out of 10 freeze.
2. If I have **no local copy** of my game in the cache, then reload - its fine.
3. Testing other games (without local copy) - its fine

I can't test games made by others because the problem just occurs if I have an outdated local copy of a game.

**Comment by TannerRogalsky** [comment]
@MadByteDE I don't seem to be experiencing this with local copies of my own projects. Is your project open source and can I get a link to it?

**Comment by MadByteDE** [comment]
http://destructivereality.de/airtaxi/
*.love can be downloaded here as well.

**Comment by TannerRogalsky** [comment]
Cool. I'll check this out when I get a chance. Thanks!

**Comment by MadByteDE** [comment]
I need to correct myself. It seems to be kinda random with a tendency to "when the game gets updated". Also get the freeze sometimes when start my game or other games without changing anything.

**Comment by TannerRogalsky** [comment]
Same as #32, I don't think this is happening any more in 0.11.

**Comment by NoAim91** [comment]
I have the same problem. 

Working with löve 0.11.1

I wonder if someone else would compile my game with love.js if the problem would still exist?
