### ISSUE TITLE
web-mari0

### ISSUE THREAD

**Issue by alugarius** [TannerRogalsky/love.js#36]
i need some help with mari0, i want to make an html/js port of it and i need help!

**Comment by TannerRogalsky** [comment]
Hey, I've already ported mari0 to web. You can see it here: http://tannerrogalsky.com/mari0/

If you're having other problems with this project, please be more specific in any issues that you open.

**Comment by alugarius** [comment]
i know its there but i cant make it with the github clone, can you give me the files that u use for the port?

**Comment by alugarius** [comment]
I follow exactly the instructions but it always freezes

**Comment by TannerRogalsky** [comment]
Sure, my site is open source and hosted on github. You'll find the relevant folder here:

https://github.com/TannerRogalsky/tannerrogalsky.github.com/tree/master/mari0

**Comment by alugarius** [comment]
cool thanks.... but why does my port crash? what i am doing wrong?

**Comment by TannerRogalsky** [comment]
I need a lot more information from you. Where does it crash? What error messages are you getting? What's your browser and OS? Are you using the debug release of this lib?

**Comment by alugarius** [comment]
i am using the master branch from github, i clone all files like it should and follow the instructions, in the debug it says my main.lua is not in the root, here a screenshot!

http://imgur.com/2tTY14f

**Comment by alugarius** [comment]
the love.js is freezing, but your version is working

**Comment by alugarius** [comment]
i am uploading my dbg folder

**Comment by TannerRogalsky** [comment]
You're not packaging the game correctly. 

Double check that you're following these steps exactly.

1. `python ../emscripten/tools/file_packager.py game.data --preload [path-to-game]@/ --js-output=game.js`
2. This should output two files: game.data and game.js into the debug folder.
3. Make you include the '@/' after the path to your game source. This will tell the file packager to place your game at the root of Emscripten's file system.
4. Make sure your [path-to-game] does not contain any non ascii characters

**Comment by alugarius** [comment]
i did,  (here my debug folder https://drive.google.com/open?id=0B-MZzriUapsTQkRlNnNvR2JXMGM
----------------------
python2 ../emscripten/tools/file_packager.py game.data --preload /home/lugarius/Downloads/future-mari0-master/game.love@/ --js-output=game.js
---------------------------

python2 because python is python3

**Comment by alugarius** [comment]
shit... have to learn markdown

**Comment by TannerRogalsky** [comment]
Try packaging the top-level game folder rather than the .love file.

**Comment by alugarius** [comment]
like this? 
python2 ../emscripten/tools/file_packager.py game.data --preload /home/lugarius/Downloads/future-mari0-master/@/ --js-output=game.js

**Comment by alugarius** [comment]
(ps : there is a new offical version of mari0 for love2d 0.10.1 https://github.com/Stabyourself/mari0)

**Comment by TannerRogalsky** [comment]
`python2 ../emscripten/tools/file_packager.py game.data --preload /home/lugarius/Downloads/future-mari0-master@/ --js-output=game.js`

It's worth noting that I made some changes to mari0 to get it to work with the port (removed networking, updated some shaders to be OpenGL ES2 compliant) so your download of future-mari0 will not work out of the box with love.js.

**Comment by alugarius** [comment]
Error: [string "boot.lua"]:432: No code to run
Your game might be packaged incorrectly
Make sure main.lua is at the top level of the zip
stack traceback:
	(tail call): ?
	[C]: in function 'error'
	[string "boot.lua"]:432: in function <[string "boot.lua"]:274>
	[C]: in function 'xpcall'

**Comment by alugarius** [comment]
your game.data is not an zip archive....
http://imgur.com/KuXIbqC

**Comment by alugarius** [comment]
can we work together on an mari0 made for the web? i could help with mappacks and you can help making the js and the game data?

**Comment by TannerRogalsky** [comment]
I'm not interested in that. Sorry.

**Comment by alugarius** [comment]
ok
can you give me the files that you used for the webversion, you said you have modded them?

**Comment by alugarius** [comment]
i want to make that alone then, but i need the source pack, and the instructions how you made it,

**Comment by alugarius** [comment]
@TannerRogalsky can you give me the game.love file and the instructions to make an working game.data file?
i want to mod it with more stuff so that is better in the web.  If you are not interested to work together, give me the last things that i need to do that alone please.

**Comment by TannerRogalsky** [comment]
Sure, the changes I made for the web port are on my fork. https://github.com/TannerRogalsky/future-mari0/tree/remove_threads
