### ISSUE TITLE
"Release it" section in the README unclear

### ISSUE THREAD

**Issue by blinry** [TannerRogalsky/love.js#38]
"Package and test your game for release." – what does this mean exactly? Do I run the same python command as before?

How would I create a web page suitable for embedding in a frame on the Ludum Dare website, for example?

**Comment by spectrenoir06** [comment]
Go to the release-compatibility or release-performance.
and use the same cmd
`python ../emscripten/tools/file_packager.py game.data --preload [path-to-game]@/ --js-output=game.js
`and you can copy the folder on your web server ( look at the index.html  to include it on your website )

**Comment by blinry** [comment]
Thanks, I figured. Maybe you would like to add this info to the README to make it clearer for everyone? :)

**Comment by s-ol** [comment]
instead, I would add a custom script that does it and remove the (huge! and unecessary) emscripten submodule.

Here's a ruby script that packs files for example: https://github.com/love2d-community/splashes/blob/master/.travis/package_game.rb

it can be easily ported to any other language (preferrably Lua I guess) and can be used to pack a .love file (which would requires slightly different ARGS to emscripten but benefits from compression)  or the 'raw' data.

**Comment by TannerRogalsky** [comment]
A more detailed explanation of how to publish a static website to various platforms is probably far beyond the scope of this project but I welcome pull requests that improve the documentation.
