### ISSUE TITLE
Player not creating the proper game.data and game.js file

### ISSUE THREAD

**Issue by bonez001** [TannerRogalsky/love.js#40]
I am done publishining a game as a html 5 game using 
python C:\Users\pc\love.js\emscripten\tools\file_packager.py game.data --preload C:\Users\pc\Desktop\Example_Game_1\ExampleGame.exe@/ --js-output=game.js

but for my second try, it doesn't output the correct file. What is worng?

**Comment by TannerRogalsky** [comment]
You should be packaging either your game folder or the .love file, not the
.exe file.

**Comment by bonez001** [comment]
Thanks for the reply.  I tried to do it but it outputs files that hvae very little data 10-500 kb. When I put the game.data and game.js to the debug folder, it always outputs the sound and the screen of one previous game. I dunno what is wrong. Thank you.

**Comment by bonez001** [comment]
I type this one
_python C:\Users\pc\love.js\emscripten\tools\file_packager.py game.data --preload C:\Users\pc\game_cards@/ --js-output=game.js_.

I dunno what is wrong. Maybe it has something to do with the conf.lua of previous game? I will try it on other pc.

**Comment by TannerRogalsky** [comment]
That looks right to me. What is the structure of the `game_cards` directory?

**Comment by bonez001** [comment]
Hello. I made it again. I dunoo what is wrong last time.
