### ISSUE TITLE
Page freezes

### ISSUE THREAD

**Issue by LucyStarlight** [TannerRogalsky/love.js#43]
The web page freezes and becomes completely unresponsive when trying to load my game.

**Comment by TannerRogalsky** [comment]
What browser/OS? What errors are sent to the browser console when running your game using the debug release?

**Comment by LucyStarlight** [comment]
Thanks for the quick reply! I'm running Windows 10, and I've tried it on both Opera and Google Chrome.
The console has the same errors in both browsers: [http://pastebin.com/i3L3Cv9F](http://pastebin.com/i3L3Cv9F)

**Comment by TannerRogalsky** [comment]
This does not look like the output from the debug release. Are you certain that you are using the love.js file from the debug folder?

**Comment by LucyStarlight** [comment]
I put my files in the debug folder and ran from there so I think so

**Comment by LucyStarlight** [comment]
It appears it was caused by my inability to read.

I had packaged my game into a .love file and used that to build the .data file. After using the folder containing the source code the page is now properly loading.

Even though the page no longer crashes, I am still getting errors keeping the game from loading properly. Would you mind taking a look at the errors for me?
[http://pastebin.com/jM6F9g1m](http://pastebin.com/jM6F9g1m)

**Comment by TannerRogalsky** [comment]
You are definitely still using one of the release builds. Notice how the functions are all 3 letters? The function `Frb`, for example, does not appear in the love.js debug build but it does appear in both release builds. Please make sure you're using the debug build which should provide more helpful errors.

**Comment by LucyStarlight** [comment]
I've re-done the entire process, and I've got more errors now x.x

[http://pastebin.com/qjXk05XK](http://pastebin.com/qjXk05XK)

**Comment by LucyStarlight** [comment]
UPDATE: After deleting the conf.lua from my project it started working.
