### ISSUE TITLE
Broken headers in Readme

### ISSUE THREAD

**Issue by Kinrany** [TannerRogalsky/love.js#46]
Headers are broken because there should be a whitespace between the hashags and the body.

`###Header` looks like

###Header

`### Header` looks like

### Header

**Comment by Kinrany** [comment]
Fixed in my own fork in ac5650ffdc65ebe4ec47abc6fbf825d46543a086

**Comment by TannerRogalsky** [comment]
Huh! This definitely worked before, I wonder what changed.

Anyway, thanks for the heads up. And for future reference, feel free to make a pull request for something like this. https://yangsu.github.io/pull-request-tutorial/
