### ISSUE TITLE
Itch.io compatibility

### ISSUE THREAD

**Issue by hollunder** [TannerRogalsky/love.js#47]
Itch.io allows for embedding html5 games. However, when I convert my gamejam-project and upload it there are issues.

1. The viewport is much smaller than it should be (should be 1024x768)
2. The game does not receive keyboard input (maybe related to this? https://github.com/itchio/itch.io/issues/58)

It would be nice if love.js was compatible with itch.io.

**Comment by JaredSartin** [comment]
1. Most likely due to styles or constraints of the itch layout

2. Does it take inputs when you click the game itself and then press a key? If it is iframe'd, this is to be expected - it's how the browser works.

**Comment by hollunder** [comment]
OK, the viewport stuff was my mistake. I found the viewport (iframe) settings and set it to 1280x1024, which works fine for this 1024x768 game+text blurb on top. The confusing part here was that the 'edit game' page changes depending on what you have selected in a dropdown on this page. I simply missed the 'embed options' that showed up after selecting 'HTML project'.

The input however seems broken. Mouse clicks work, but it does not get keyboard focus.
I made a test project on itch.io: https://murks.itch.io/cookiest-lovejs-test

**Comment by TannerRogalsky** [comment]
Keyboard works for me if you click inside the iframe first to give it focus. Nothing I can reliably do about that, though. There are ways to set focus on the canvas element with some JavaScript on the page but that's not something that should be happening at the framework level.

**Comment by hollunder** [comment]
It did not work for me in either Firefox or Chrome (both on Linux).
A click on buttons works, keyboard, even after the clicks, does not.

**Comment by TannerRogalsky** [comment]
Click inside the iframe but outside the canvas.

**Comment by hollunder** [comment]
Ok, thanks, that works, but it is certainly unexpected behaviour from a user perspective. The canvas is inside the iframe after all.

**Comment by TannerRogalsky** [comment]
I appreciate where you're coming from but it's outside of my control. Like I said, you can probably get it working with some JS specific to that page setup but it can't be easily generalized to every situation.

**Comment by hollunder** [comment]
Ok, thanks. I'm just not familiar enough with JS and browser input specifics to fix this myself.

**Comment by hollunder** [comment]
OK, I hacked in a window.focus(), which seems to have done the trick. It's probably not the best place to put it, but I added it at the end of the Module thing.

```
      var Module = {
        buffer: new ArrayBuffer(32*1024*1024*2),
        TOTAL_MEMORY: 32*1024*1024*2,
	arguments: ['./'],
...
        monitorRunDependencies: function(left) {
          this.remainingDependencies = left;
          this.totalDependencies = Math.max(this.totalDependencies, left);
          Module.setStatus(left ? 'Preparing... (' + (this.totalDependencies-left) + '/' + this.totalDependencies + ')' : 'All downloads complete.');
          window.focus();
        }
      };
```
