### ISSUE TITLE
Attempt to call nil value

### ISSUE THREAD

**Issue by egordorichev** [TannerRogalsky/love.js#49]
Was testing your awesome framework before game jam, packed my game to a zip file.
Did all, that is in README. All worked fine. Besides, the lua:

![](http://i.imgur.com/FjsNtOu.png)

[__Game can be found here__](https://github.com/egordorichev/cga17) 

Tryed to pass folder with game. Same result.
How to fix? Thanks.

**Comment by TannerRogalsky** [comment]
There's a Lua error in your code AKA you're doing something unsupported by the web version. Maybe lurker? That lib is really intrusive and you shouldn't use it in your release version anyway. 

I'd just remove things from your game until it works.

**Comment by egordorichev** [comment]
Oh, lurker.... Ok, will try to remove it. Thanks.

**Comment by egordorichev** [comment]
Hey! I've created new empty lua app:

```
function love.draw()
	love.graphics.print("Hello!", 10, 10)
end
```

Packed it into game.zip. Love can run it. I'm packing it with this command:

```
python2.7 ../emscripten/tools/file_packager.py game.data --preload game.zip@/ --js-output=game.js
```

(Game is in debug folder)

Running server:

```
python2.7 -m SimpleHTTPServer 8000
```
![screenshot_2017-06-11_16-49-08](https://user-images.githubusercontent.com/7851390/27011539-4784278c-4ec6-11e7-8634-b8371809e2b5.png)

**Comment by TannerRogalsky** [comment]
That invocation of file_packager is probably not what you want.
`--preload game.zip@/` loads game.zip at the root directory of emscripten's in-memory file system.

If you want to use a .zip, run `--preload game.zip@/game.zip` and then change the arguments field on the Module object in the html page to `['./game.zip']` to tell the application where the game data is.

**Comment by egordorichev** [comment]
>  and then change the arguments field on the Module object in the html page to ['./game.zip']

Sorry, where that can be changed?

**Comment by egordorichev** [comment]
> var Module = {
        preRun: [],
        postRun: [],
        arguments: ['./game.zip'],

And

> python2.7 ../emscripten/tools/file_packager.py game.data --preload game.zip@/game.zip --js-output=game.js

Same result.

**Comment by egordorichev** [comment]
Oh, I found this: https://www.npmjs.com/package/love.js
Will try it out.
