### ISSUE TITLE
MP3s don't work.

### ISSUE THREAD

**Issue by TannerRogalsky** [TannerRogalsky/love.js#5]
Love.js is currently compiled with MP3 support disabled. I haven't looked into if that decoder can be compiled with emscripten yet.

**Comment by Bobbyjoness** [comment]
For audio (and potentially video) is it possible to have a JavaScript code path that would just let the browser play the audio. This should have mp3s and such working. It should also potentially have streaming work as well.

**Comment by TannerRogalsky** [comment]
Getting MP3s working should just be a matter of compiling their mpg123 dependency and linking it in. Just haven't gotten around to it yet.

**Comment by TannerRogalsky** [comment]
Resolved by #7
