### ISSUE TITLE
bad name in getProcAddress: glIsVertexArrayOES,glIsVertexArray

### ISSUE THREAD

**Issue by danbolt** [TannerRogalsky/love.js#59]
On the latest revision (38ab12b) on `master`, I try running the following game:
```lua
function love.draw()
  love.graphics.setColor(1, 0, 0, 1)
  love.graphics.rectangle("fill", 100, 100, 100, 100)
end
```
Upon running in debug, I'm met with a blank screen and the following console output:

![screen shot 2018-05-14 at 10 09 49 pm](https://user-images.githubusercontent.com/1205433/40037714-8d561890-57c3-11e8-8f87-e186bc198c08.png)

Perhaps there's something I'm missing? It looks like an issue to do with SDL/WebGL, but I'm not 100% sure. Would updating Emscripten fix this?

**Comment by kiwec** [comment]
Same on 0.11 branch, seems like it renders some textures before freezing.

![2019-10-18-205321_641x193_scrot](https://user-images.githubusercontent.com/1957540/67120315-59eeb180-f1e9-11e9-9fd5-a5b11124f24b.png)

Using firefox on linux. Chromium throws a lot more gl* errors.

**Comment by xharris** [comment]
![error](https://i.imgur.com/fRDLbfN.png)
I'm having a similar issue. Lovejs 0.11 worked perfectly for me before. Did something change with web browsers in general to break love.js?
