### ISSUE TITLE
Up/down arrows still scroll page when the game is focused

### ISSUE THREAD

**Issue by davisdude** [TannerRogalsky/love.js#6]
I tried "focusing" on Mr. Rescue by clicking the game area. When I used the arrows, the screen moved up and down too. This also happens with "Friendshape"

Using Google Chrome. This does not happen in Firefox.

**Comment by TannerRogalsky** [comment]
Good catch! My resolution was too large to experience that. I'll look into it.

**Comment by TannerRogalsky** [comment]
Fixed by f806f40.

**Comment by davisdude** [comment]
Now you can't use the arrow keys to navigate the page itself.
